
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 03 17:31:51 CST 2020
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ADJ_OBDIENTE = 9;
  public static final int ADJ_BONITA = 10;
  public static final int VERBO_CORRE = 8;
  public static final int ARTICULO_EL = 2;
  public static final int EOF = 0;
  public static final int ARTICULO_LA = 3;
  public static final int NOMBRE_CARRO = 6;
  public static final int NOMBRE_NINA = 4;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 12;
  public static final int ADJ_RAPIDO = 11;
  public static final int VERBO_ES = 7;
  public static final int NOMBRE_NINO = 5;
}

