
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 30 21:03:18 CST 2025
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 18;
  public static final int PUNTO = 13;
  public static final int CADENA = 22;
  public static final int IGUAL = 16;
  public static final int SEMI = 10;
  public static final int WRITELN = 5;
  public static final int END = 4;
  public static final int USES = 7;
  public static final int ID = 21;
  public static final int POR = 19;
  public static final int WRITE = 6;
  public static final int PROGRAM = 2;
  public static final int NUM = 23;
  public static final int DP = 11;
  public static final int BEGIN = 3;
  public static final int COMA = 12;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int CONST = 9;
  public static final int error = 1;
  public static final int PC = 15;
  public static final int PA = 14;
  public static final int MAS = 17;
  public static final int VAR = 8;
}

